// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyurkrtzgjupbyhgwseu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95dXJrcnR6Z2p1cGJ5aGd3c2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTE5MTYsImV4cCI6MjA2MDE4NzkxNn0.UIfOEVNQ7cfpan-7c7APY5I1k129ChRSCYP0eBDQZ5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);